# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Rose-DateTime
version:      0.531
version_from: lib/Rose/DateTime.pm
installdirs:  site
requires:
    DateTime:                      0
    Rose::Object:                  0.82

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
